### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by galdor** [s-expressionists/dpans#1]
I just discovered this repository. The COPYING file indicates that all files are in the public domain. Where does this come from ? The ANSI specification is, as far as I know, proprietary, and the only version of the Hyperspec I was aware of is the HTML version [published by LispWorks](http://www.lispworks.com/documentation/common-lisp.html) with [very limited rights](http://www.lispworks.com/documentation/HyperSpec/Front/Help.htm#Legal).

I was hoping to convince LispWorks to relax terms to allow anyone to re-publish the Hyperspec with modifications, in order to improve readability (layout, colors, fonts, etc.). But if LispWorks only own the right on the HTML version, it might be simpler to start from TeX sources.

**Comment by robert-strandh** [comment]
This is not final ANSI standard, but the dpANS, which means the "draft
proposal" for the standard.  The draft proposal is almost identical to
the final standard, but it is in the public domain.  I believe the
HyperSpec is also based on the draft proposal.

Jan Morningen has already created the tools for parsing the TeX files,
and one of the results is an HTML version of the dpANS, so you don't
have to actually do anything, except enjoy the result.

**Comment by galdor** [comment]
Do you have a link for these tools ? I cannot find them in this repository or in [his repositories](https://github.com/scymtym).

**Comment by robert-strandh** [comment]
I will let Jan answer that question when he shows up.

**Comment by dkochmanski** [comment]
https://github.com/scymtym/dpans-conversion

**Comment by galdor** [comment]
Thank you, I will have a look.

**Comment by scymtym** [comment]
@galdor You may want to have a look at https://www.youtube.com/watch?v=aZn8dKmXbOw for context.
